name: Sync to Codeberg

on:
  push:
    branches: [ Jsnzkpg ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        env:
          TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg https://Jsnzkpg:${TOKEN}@codeberg.org/Jsnzkpg/Jsnzkpg.git
          git push -f codeberg HEAD:Jsnzkpg
